name: Terraform Prod Deployment

on:
  workflow_dispatch:

jobs:
  tf-prod-apply:
    name: TF PROD APPLY
    uses: kyalders/terraform_workflows/.github/workflows/terraform.yml@main
    if: github.event_name == 'workflow_dispatch'
    with:
      env: prod
      tf-path: ./
      token-files: '["./provider.tf"]'
      tf-plan: false
      tf-apply: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
